version: "3.8"

services:
  pdrm-dashboard:
    build: .
    container_name: pdrm-asset-dashboard
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./data:/app/data # Optional: for persistent data storage
    restart: unless-stopped
    networks:
      - pdrm-network

networks:
  pdrm-network:
    driver: bridge
